version: '3.8'

services:
  haskell-app:
    build: .
    container_name: haskell-learning-app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      # Для разработки - монтируем файлы напрямую
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./styles.css:/usr/share/nginx/html/styles.css:ro
      - ./script.js:/usr/share/nginx/html/script.js:ro
    labels:
      - "com.docker.compose.project=haskell-learning"
      - "description=Haskell learning app for mobile developers"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Дополнительный сервис для разработки с hot-reload
  haskell-dev:
    image: node:18-alpine
    container_name: haskell-dev-server
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npx http-server -p 3000 -o --cors
    profiles:
      - dev

networks:
  default:
    name: haskell-network 